apiVersion: v1
kind: Service
metadata:
  name: milestone-project-service
spec:
  type: LoadBalancer
  selector:
    app: milestone-project-2
  externalIPs:  
    - 172.19.57.19
  ports:
    - name: webtool-port
      protocol: TCP
      port: 80
      targetPort: 3002
    - name: node-api-port
      protocol: TCP
      port: 8081
      targetPort: 3000
    - name: py-api-port
      protocol: TCP
      port: 8082
      targetPort: 3001
